include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - 'example/**'
    - 'build/**'
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - '**/*.config.dart'
  errors:
    invalid_annotation_target: ignore
    use_build_context_synchronously: ignore