name: flutter_amazon_iap
description: Amazon In-app purchase for Flutter use Amazon AppStore SDK
version: 0.0.1
homepage: https://github.com/tuyennvt/flutter_amazon_iap.git

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.4
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  freezed: ^2.3.3
  json_serializable: ^6.6.2
  build_runner: ^2.3.3

flutter:
  plugin:
    platforms:
      android:
        package: com.tuyennvt.flutter_amazon_iap
        pluginClass: FlutterAmazonIapPlugin